def changeToCode(stateName):
    codesState = {'Andhra Pradesh': 1,
     'Ladakh': 17,
     'Kerala': 16,
     'Karnataka': 15,
     'Jammu and Kashmir': 13,
     'Jharkhand': 14,
     'Haryana': 11,
     'Himachal Pradesh': 12,
     'Lakshadweep': 18,
     'Gujarat': 10,
     'Dadra and Nagar Haveli and Daman and Diu': 7,
     'Delhi': 8,
     'Chhattisgarh': 6,
     'Chandigarh': 5,
     'Bihar': 4,
     'Assam': 3,
     'Goa': 9,
     'Maharashtra': 20,
     'Meghalaya': 22,
     'Manipur': 21,
     'West Bengal': 35,
     'Uttarakhand': 34,
     'Uttar Pradesh': 33,
     'Tripura': 32,
     'Tamil Nadu': 30,
     'Andaman and Nicobar Islands': 0,
     'Telangana': 31,
     'Rajasthan': 28,
     'Puducherry': 26,
     'Punjab': 27,
     'Odisha': 25,
     'Nagaland': 24,
     'Mizoram': 23,
     'Madhya Pradesh': 19,
     'Sikkim': 29,
     'Arunachal Pradesh': 2}    
    return codesState[stateName]
